name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build Java application
        run: |
          ./mvnw package -DskipTests=true

      - name: Build Docker image
        run: |
          docker build -t my-image .
          docker tag my-image:latest my-registry/my-image:latest

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push my-registry/my-image:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml