name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 20
        uses: actions/setup-java@main
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t my-image .
          docker tag my-image:latest 349162464757.dkr.ecr.eu-north-1.amazonaws.com/my-image:latest
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 349162464757.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Docker image to ECR
        run: |
            docker push 349162464757.dkr.ecr.eu-north-1.amazonaws.com/my-image:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml